added port and path
CodeSEAS/lory-gateway pull request #2
Opened 2021-02-05 05:22 UTC by CodeSEAS

The first springboot page launched

2021-02-05 05:42 UTC, stargrep reviewed
can you please make sure not include .gradle/ and .DS_Store files in the commit?
For .gradle files, we can just remove the whole folder.
For .DS_Store can you add to git ignore?

2021-02-05 05:44 UTC, stargrep requested changes

2021-02-05 05:44 UTC, stargrep commented on .gradle/buildOutputCleanup/cache.properties
> +gradle.version=6.5
No need

2021-02-05 05:44 UTC, stargrep commented on src/main/java/com/lory/gateway/hello.java
> +public class hello {
class name should be Capitalized

2021-02-05 05:44 UTC, stargrep commented on src/main/java/com/lory/gateway/hello.java
> +    @RequestMapping(value="/hello", method = RequestMethod.GET) //定义路由
Please change comments to be English

2021-02-05 05:44 UTC, stargrep commented on src/main/resources/application.properties
> +server.servlet.context-path=/lory
Don't think we need the extension? or Maybe `api-gateway` is better?

2021-02-06 03:26 UTC, CodeSEAS commented
The changes have been made according to the recommendations. Thanks:)

2021-02-06 03:40 UTC, stargrep approved these changes

2021-02-06 03:40 UTC, stargrep commented
accept to unblock.

2021-02-06 03:40 UTC, merged